//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telematics.Server.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVehicle
    {
        public UserVehicle()
        {
            this.VehicleSpeeds = new HashSet<VehicleSpeed>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<VehicleSpeed> VehicleSpeeds { get; set; }
    }
}
