//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telematics.Server.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSpeed
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int VehicleID { get; set; }
        public decimal Lat { get; set; }
        public decimal Lon { get; set; }
        public decimal Speed { get; set; }
        public byte[] EventTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserVehicle UserVehicle { get; set; }
    }
}
