
USE [master]
GO

/****** Object:  Database [geo]    Script Date: 27/10/2013 19:25:04 ******/
DROP DATABASE [geo]
GO

/****** Object:  Database [geo]    Script Date: 27/10/2013 19:25:04 ******/
CREATE DATABASE [geo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'geo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\geo.mdf' , SIZE = 367616KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'geo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\geo_log.ldf' , SIZE = 353216KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [geo] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [geo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [geo] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [geo] SET ANSI_NULLS OFF
GO

ALTER DATABASE [geo] SET ANSI_PADDING OFF
GO

ALTER DATABASE [geo] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [geo] SET ARITHABORT OFF
GO

ALTER DATABASE [geo] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [geo] SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE [geo] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [geo] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [geo] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [geo] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [geo] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [geo] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [geo] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [geo] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [geo] SET  DISABLE_BROKER
GO

ALTER DATABASE [geo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [geo] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [geo] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [geo] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [geo] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [geo] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [geo] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [geo] SET RECOVERY FULL
GO

ALTER DATABASE [geo] SET  MULTI_USER
GO

ALTER DATABASE [geo] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [geo] SET DB_CHAINING OFF
GO

ALTER DATABASE [geo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [geo] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [geo] SET  READ_WRITE
GO

USE [master]
GO

/****** Object:  Login [CRISPINPAD\TelematicsAppPool]    Script Date: 27/10/2013 19:26:29 ******/
DROP LOGIN [CRISPINPAD\TelematicsAppPool]
GO

USE [geo]
GO

/****** Object:  User [TelematicsUser]    Script Date: 27/10/2013 19:26:13 ******/
DROP USER [TelematicsUser]
GO

USE [geo]
GO

/****** Object:  Table [dbo].[User]    Script Date: 27/10/2013 19:23:48 ******/
DROP TABLE [dbo].[User]
GO

/****** Object:  Table [dbo].[User]    Script Date: 27/10/2013 19:23:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [geo]
GO

ALTER TABLE [dbo].[UserVehicle] DROP CONSTRAINT [FK_UserVehicle_User]
GO

/****** Object:  Table [dbo].[UserVehicle]    Script Date: 27/10/2013 19:23:55 ******/
DROP TABLE [dbo].[UserVehicle]
GO

/****** Object:  Table [dbo].[UserVehicle]    Script Date: 27/10/2013 19:23:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [geo]
GO

ALTER TABLE [dbo].[VehicleSpeed] DROP CONSTRAINT [FK_VehicleSpeed_UserVehicle]
GO

ALTER TABLE [dbo].[VehicleSpeed] DROP CONSTRAINT [FK_VehicleSpeed_User]
GO

/****** Object:  Table [dbo].[VehicleSpeed]    Script Date: 27/10/2013 19:24:00 ******/
DROP TABLE [dbo].[VehicleSpeed]
GO

/****** Object:  Table [dbo].[VehicleSpeed]    Script Date: 27/10/2013 19:24:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER DATABASE [geo] SET DELAYED_DURABILITY = DISABLED 

GO

--Syntax Error: Incorrect syntax near DELAYED_DURABILITY.
--
--ALTER DATABASE [geo] SET DELAYED_DURABILITY = DISABLED 



GO
