//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telematics.Server.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserVehicles = new HashSet<UserVehicle>();
            this.VehicleSpeeds = new HashSet<VehicleSpeed>();
        }
    
        public int ID { get; set; }
        public string DeviceID { get; set; }
    
        public virtual ICollection<UserVehicle> UserVehicles { get; set; }
        public virtual ICollection<VehicleSpeed> VehicleSpeeds { get; set; }
    }
}
